name: Auto Deploy Resume App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Clean up old app
          rm -rf ~/scp-resume-app

          # Clone latest repo
          git clone https://github.com/Abhijoshy/scp-resume-app.git
          cd scp-resume-app

          # Set up venv and install dependencies
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          # Kill previous gunicorn process if exists
          pkill gunicorn || true

          # Run app using gunicorn
          nohup venv/bin/gunicorn --bind 0.0.0.0:5000 app:app > log.txt 2>&1 &
